# Generated by Django 5.0.9 on 2024-12-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_created_6393be_idx',
        ),
    ]
